- aseba/common/CMakeLists.txt
- aseba/common/zeroconf/CMakeLists.txt
- aseba/compiler/CMakeLists.txt
- aseba/switches/http/CMakeLists.txt
- aseba/switches/http2/CMakeLists.txt
- aseba/transport/buffer/CMakeLists.txt
- aseba/transport/dashel_plugins/CMakeLists.txt
- aseba/vm/CMakeLists.txt
Aseba is more a set of tools than a frameworks.
We do not make ABI or API stability guarantees
except for some very specific classes.
Therefore we should not encourage people to use
aseba as libraries.
Modification, research works and new targets should rather
be added in-tree.
> Do not copy headers in the installation folder

- aseba/switch/usbdevice.cpp
libusb_detach_kernel_driver is a linux specific method
> Fix usb device on windows.

- .appveyor.yml
- aseba/flatbuffers/fb_message_ptr.h
- aseba/flatbuffers/thymio.fbs
- aseba/qt-thymio-dm-client-lib/thymio-api.h
- aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclient.cpp
- aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclientendpoint.cpp
- aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclientendpoint.h
- aseba/switch/CMakeLists.txt
- aseba/switch/app_endpoint.h
- aseba/switch/flatbuffers_messages.h
- aseba/switch/tdm.h
- js/CMakeLists.txt
- js/thymio.js
- js/thymio_generated.js
When connecting to the TDM, a client *MUST* send a
`ConnectionHandshake` message which has 2 fields
* minProtocolVersion: the minimum protocol version supported by
the client
* protocolVersion:  the protocol version of the client
The server will respond with the same messages where
* minProtocolVersion: the minimum protocol version supported by
the server
* protocolVersion:  the protocol version selected by the server
for this session
* If the server respond with protocolVersion == 0,
the handshake failed and the connection is going to be closed.
> Implement TDM protocol versionning

- aseba/launcher/src/CMakeLists.txt
- aseba/launcher/src/launcher.cpp
- aseba/launcher/src/launcher.h
- aseba/launcher/src/main.cpp
- aseba/launcher/src/tdmsupervisor.cpp
- aseba/launcher/src/tdmsupervisor.h
Closes #205
This is a minimalistic approach
* Look for the tdm in launcher directory & PATH
* Launch it
* Detect if already launched
* Relaunched when TDM crashes
* Stop on exit
Not managed:
* No UI feedback
* Do not detect whether apps are connected on the TDM
* No communicayion at all with the TDM
> Launch the TDM from the launcher

- aseba/flatbuffers/thymio.fbs
- aseba/thymio-device-manager/app_endpoint.h
- aseba/thymio-device-manager/flatbuffers_message_reader.h
- aseba/thymio-device-manager/tdm.h
- js/thymio_generated.js
This allow to protect against wrong actors and let embeded devices
allocate a single fixed size buffer.
Closes #246
> [TDM] Advertise a maximum packet size

- aseba/clients/studio/DashelTarget.cpp
- aseba/common/consts.h
- aseba/common/msg/NodesManager.cpp
Dashel based-clients required the exact same protocol
version for both the device and the client.
This is not sensible because it prevents
updating the firmwares independently of the client.
Instead the protocol should be backward compatible
with older endpoint (and protocols 5,6 and 7 are).
This patch provides and check against
ASEBA_MAX_TARGET_PROTOCOL_VERSION, which is an arbitrary value
should a non backward-compatible protocol change ever be needed.
> [Aseba] More lenient protocol version check

- aseba/thymio-device-manager/aseba_node.cpp
@mbonani this is the fix for thymio proto 5 - I think proto 4 won't work at all but try.
You can merge that once it builds
> Give a non null uuid to old thymios

- aseba/thymio-device-manager/aseba_endpoint.h
Sending the vm description might take several seconds
which makes the whole network unresponsive in the
meantime
> Increase the delay before considering a node disconnected

- aseba/common/consts.h
- aseba/common/msg/msg.cpp
- aseba/common/msg/msg.h
- aseba/thymio-device-manager/aseba_description_receiver.h
- aseba/thymio-device-manager/aseba_endpoint.h
- aseba/transport/buffer/vm-buffer.c
- aseba/transport/buffer/vm-buffer.h
- aseba/vm/vm.c
- aseba/vm/vm.h
- tests/compiler/asebavmdummycallbacks.cpp
New protocol version: 8
New message ASEBA_MESSAGE_GET_NODE_DESCRIPTION_FRAGMENT, ask the node
to split its description.
Fragment -1 is the general description (message Aseba::Description)
Fragments 0+ are the individual functions, events,
variables of the device.
> Send the description in fragments

- aseba/clients/studio/VariablesModel.cpp
- aseba/clients/studio/VariablesModel.h
Ensures the UI doesn't freeze when receiving large-ish variable
lists
> Limit numbers of calls to VariableModel::dataChanged

- aseba/flatbuffers/thymio.fbs
- aseba/launcher/src/CMakeLists.txt
- aseba/launcher/src/launcherwindow.cpp
- aseba/launcher/src/launcherwindow.h
- aseba/launcher/src/main.cpp
- aseba/launcher/src/tdmsupervisor.cpp
- aseba/launcher/src/tdmsupervisor.h
- aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclient.cpp
- aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclient.h
- aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclientendpoint.cpp
- aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclientendpoint.h
- aseba/thymio-device-manager/app_endpoint.h
- aseba/thymio-device-manager/main.cpp
- js/thymio_generated.js
Killing the TDM isn't nice an does not work
on windows depending on the installation directory.
Instead, when closing the launcher, it will send a
shutdown request to the localhost's TDM so that it
can shutdown cleanly.
> When closing studio, send a shutdown message to the TDM.

- aseba/launcher/src/qml/Applications.qml
- aseba/launcher/src/qml/ThymioSelectionDeviceDelegate.qml
- aseba/qt-thymio-dm-client-lib/thymiodevicesmodel.cpp
- aseba/qt-thymio-dm-client-lib/thymiodevicesmodel.h
- aseba/qt-thymio-dm-client-lib/thymionode.cpp
- aseba/qt-thymio-dm-client-lib/thymionode.h
Unusable devices are:
* Devices in a group if the application doesn't support that
* Devices busy if the application doesn't support watch mode
Fixes #403
> [Launcher] Prevent unusable device to be selected

- aseba/thymio-device-manager/aseba_endpoint.h
- aseba/thymio-device-manager/aseba_node_registery.cpp
- aseba/thymio-device-manager/aseba_node_registery.h
This allow us to deal with devices connected in
wireless and usb at the same time
> [TDM] Disconnect the old node when there are duplicated UUID.

- aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclientendpoint.cpp
QObjects should not be deleted directly.
Fixes #440
Fixes #404
> Fix crash of qt apps when a TDM is disconnected.

- aseba/qt-thymio-dm-client-lib/thymionode.cpp
Fixes #440
A signal was attached to a lambda slot without an associated
object, causing the signat to be sent long after
the object has been destroyed.
> [Qt API] Fix crash when an endpoint is disconnected.

- aseba/launcher/src/qml/webview_native.qml
Load an empty webpage before destroying the webview
to avoid a crash on osx
> Fix webview crash on OSX

- aseba/launcher/src/launcher.cpp
Let the qml engine run, which leaks
Fixes #495
> 'Fix' a crash on osx when closing a webview

- aseba/launcher/src/qml/SettingsMenu.qml
Make sure the settings menu stays on the right when
resizing the window.
Because we are animating that menu, we cannot use anchors
so the solution is to listen to width changes and reposition
the menu
A bit hacky...
> [Launcher] anchor the settings menu

- Brewfile
- CMakeModules/cpp_features.cmake
- aseba/launcher/src/launcher.cpp
- azure-pipelines.yml
the real issue is the version of Qt on the build machine. Automatically the version 5.14 is used, but this version is not compatible with macos 10.12
> Defect#752 - boost 1.72 make a crash on macosx 10.12

- azure-pipelines.yml
Pointing the specific version of boost
as 1.72.0
in order to be compliant with mac_os 10.14 specific to the latest build machine configuration
The mod is obtained by the azure_pipeline custom homebrew callout
> fixing compilation bug due to boost

- aseba/thymio-device-manager/aseba_node_registery.cpp
- aseba/thymio-device-manager/aseba_node_registery.h
- aseba/thymio-device-manager/main.cpp
* Make sure the even loop was entered before trying to announce
the TDM on zeroconf.
* Make sure the server are accepting connections by the TDM is
announced on zero conf.
* Refresh the announce every few seconds in case there
was some spurious failure.
This changes should make zero conf a bit more reliable and
avoid some of the issues where the launcher doesn't see the
TDM
I have spend a significant amount of time trying to find race conditions, undefined behavior and so forth and I am not seeing anything abnormal.
I have compared aware with other zero conf implementations ( notably the one used by the launcher) and I'm not seeing anything weird.
There was an issue where we  could try to announce on zero conf before the client was started if the event loop had not been started yet. I am …
> Improve zero conf announce reliability.
