aseba/switch/aseba_endpoint.h, aseba/switch/aseba_node.h, aseba/switch/aseba_node_registery.cpp, aseba/switch/aseba_node_registery.h
Implement broadcasting for thymio 2 nodes
Filter CmdMessags to be sent only to the requested target
Bi directional node id remapping
=> Implement broadcasting

aseba/switch/usbacceptor.cpp, aseba/switch/usbacceptor.h
This is mainly for windows, on which libusb do not support
hotplug detection yet.
If the hotplug callback can not be registered, start a timer
and list compatible devices every second.
=> Active usb devices listing on systems that do not support hotplug

aseba/switch/aseba_endpoint.h, aseba/switch/aseba_node_registery.cpp, aseba/switch/aseba_node_registery.h
This is not the right approach.
=> Remove broadcasting.

aseba/flatbuffers/CMakeLists.txt, aseba/flatbuffers/fb_message_ptr.h, aseba/flatbuffers/thymio.fbs, aseba/switch/app_endpoint.h, aseba/switch/aseba_endpoint.h, aseba/switch/aseba_node.cpp, aseba/switch/aseba_node.h, aseba/switch/aseba_node_registery.cpp, aseba/switch/aseba_tcpacceptor.cpp, aseba/switch/aseba_tcpacceptor.h, aseba/switch/flatbuffers_message_reader.h, aseba/switch/flatbuffers_message_writer.h, aseba/switch/main.cpp, aseba/switch/serialserver.cpp, aseba/switch/usbdevice.cpp, aseba/switch/usbdevice.h, aseba/switch/usbserver.cpp, js/thymio.js, js/thymio_generated.js
This is a clean PR for the switch only, based on #188 
* Handle tcp & serial better
* Device name
* Device type
* Simulated nodes
=> Switch modifications for the launcher

aseba/switch/aseba_tcpacceptor.cpp
When auto discovering aseba endpoints on tcp,
ignore the one that are on remote machines
#203
=> Ignore aseba on remote endpoints.

CMakeModules/boost.cmake, aseba/switch/CMakeLists.txt, aseba/switch/main.cpp
Lock files are properly released after a crash
=> Use a lock file instead of a system mutex

aseba/flatbuffers/thymio.fbs, aseba/switch/flatbuffers_messages.h, js/thymio_generated.js
=> Add index of aseba variables/events/functions

aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclient.cpp
=> [Qt Api] connect via ip rather than host

aseba/launcher/src/launcher.cpp, aseba/launcher/src/launcher.h, aseba/launcher/src/qml/Applications.qml
see https://bugreports.qt.io/browse/QTBUG-55300
=> [Launcher] Fix for url fragment stripped on windows

aseba/launcher/src/launcher.cpp
=> [Launcher] Create html redirection files in a temporary dir

aseba/thymio-device-manager/aseba_message_parser.h
I thought I was being clever gathering the header fields
into a SerializationBuffer, that turned out to be a pretty
bad idea...
=> [TDM] Fix crash when deserializing Aseba::UserMessage

aseba/thymio-device-manager/usbdevice.h
This reverts commit b23f6d4c5fcb72c9285ef462a6485b5cad34100b.
=> Revert "Fix compilation with gcc 6"

.appveyor.yml, aseba/CMakeLists.txt, aseba/flatbuffers/thymio.fbs, aseba/launcher/src/CMakeLists.txt, aseba/launcher/src/qml/ThymioSelectionDeviceDelegate.qml, aseba/qt-thymio-dm-client-lib/CMakeLists.txt, aseba/qt-thymio-dm-client-lib/qml/quickrequest.cpp, aseba/qt-thymio-dm-client-lib/qml/quickrequest.h, aseba/qt-thymio-dm-client-lib/request.cpp, aseba/qt-thymio-dm-client-lib/request.h, aseba/qt-thymio-dm-client-lib/thymio-api.h, aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclientendpoint.cpp, aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclientendpoint.h, aseba/qt-thymio-dm-client-lib/thymionode.cpp, aseba/qt-thymio-dm-client-lib/thymionode.h
This type acts like a future for the protocol response messages.
Also provide QML bindings.
=> [Qt Api] Introduce a Request type.

.travis.yml, aseba/CMakeLists.txt, aseba/clients/studio/NodeTab.cpp
=> Do not start watching variables if the synchronize checkbox

aseba/qt-thymio-dm-client-lib/request.h
=> Fix memory usage

aseba/thymio-device-manager/aseba_tcpacceptor.cpp
Regression introduced by becf90df86e65
=> Fix the TDM actively spinning while waiting for tcp client

aseba/clients/studio/main.cpp
=> Studio : add command line usage

aseba/clients/vpl/ThymioVPLApplication.cpp, aseba/clients/vpl/ThymioVisualProgramming.cpp, aseba/clients/vpl/ThymioVisualProgramming.h
=> [VPL] Disable run/stop button when device is not ready

aseba/thymio-device-manager/aseba_node_registery.cpp
=> [TDM] Handle duplicated uuid

aseba/thymio-device-manager/app_endpoint.h, aseba/thymio-device-manager/aseba_node.cpp, aseba/thymio-device-manager/aseba_node.h
=> [TDM] Fix force stop

aseba/clients/qtcommon/images/vpl/error.svg, aseba/launcher/src/qml/ThymioSelectionDeviceDelegate.qml
=> [Launcher] launch app on double click on device

aseba/clients/vpl/ThymioVPLApplication.cpp
=> [VPL] Show device name in window's title

aseba/clients/vpl/ThymioVisualProgramming.cpp
=> [VPL] Fix warning message when switching mode (#77)

aseba/thymio-device-manager/aseba_endpoint.h
Systematically keep some messages at the back of the write queue
to improve scratch responsivness.
=> [TDM] Deprioritize system messages to increase responsivness

aseba/thymio-device-manager/app_endpoint.h
This fixes a regression introduced in 325778b89
Fixes #439
=> [TDM] Correctly report the when a node is ready

aseba/thymio-device-manager/app_endpoint.h
This fixes a regression introduced in 325778b
=> [TDM] Correctly report uuid changes

aseba/thymio-device-manager/serialacceptor.cpp
=> [TDM] fix leak

aseba/clients/qtcommon/CMakeLists.txt, aseba/clients/qtcommon/MobsyaApplication.cpp, aseba/clients/qtcommon/MobsyaApplication.h, aseba/clients/studio/MainWindow.cpp, aseba/clients/studio/MainWindow.h, aseba/clients/studio/main.cpp, aseba/clients/vpl/ThymioVPLApplication.cpp, aseba/clients/vpl/ThymioVPLApplication.h, aseba/clients/vpl/thymiovpl.cpp, aseba/launcher/src/CMakeLists.txt, aseba/launcher/src/launcher.cpp, aseba/launcher/src/launcher.h, aseba/launcher/src/launcher.mm, aseba/launcher/src/qml/Applications.qml, osx/AsebaPlayground.entitlements, osx/AsebaStudio.entitlements, osx/ThymioVPLClassic.entitlements, osx/createbundle.sh
NSTask doesn't work properly in the sandbox.
Instead we register a custoom url handler which we use
to open vpl and studio
=> Properly sandbox applications on OSX

flatpak/org.mobsya.ThymioSuite.json, menu/freedesktop/thymio-launcher.desktop
I've modified the desktop files so that they can be exported by the flatpak to the user.
=> Adding Desktop icons to the flatpak

aseba/clients/studio/NodeTab.cpp
=> Load the editor buffer in device before writing it to memory

aseba/launcher/src/launcher.cpp, aseba/launcher/src/launcher.h, aseba/launcher/src/qml/ThymioSelectionView.qml, aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclient.cpp, aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclient.h
Fixes #472 
@cbarraud @mbonani @Vincebecker I'll need a stable url that we can point to FAQ on how to start avahi (Linux) and bonjour(windows) - is there a way to setup stable redirections on thymio.org or mobsya.org ?
=> [WIP] Display an error message when avahi or bonjour isn't running

aseba/launcher/src/qml/ThymioSelectionDeviceDelegate.qml, aseba/launcher/src/qml/ThymioSelectionView.qml
=> Fix Device selection

aseba/clients/studio/VariablesModel.cpp
=> Fix build on fedora

aseba/qt-thymio-dm-client-lib/thymionode.cpp
=> Simulated thymio cannot be upgraded

.appveyor.yml, CMakeLists.txt, azure-pipelines.yml, windows/NSIS.template.in
=> Use the name Thymio Suite consistantly for the launcher and installer

aseba/launcher/src/launcher.cpp, aseba/launcher/src/qml/ThymioSelectionView.qml
=> Use the system browser on Sierra to launch webapps

aseba/targets/playground/PlaygroundViewer.cpp
=> [Playground] Set viewer minimum size

aseba/launcher/src/qml/ThymioSelectionDeviceDelegate.qml, aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclient.cpp, aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclientendpoint.cpp, aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclientendpoint.h, aseba/qt-thymio-dm-client-lib/thymionode.cpp, aseba/qt-thymio-dm-client-lib/thymionode.h
=> [Launcher] Display the name of each device endpoint in a tooltip

aseba/clients/vpl/Scene.cpp
=> [VPL] Fix error display

aseba/launcher/src/qml/EditableDeviceNameInput.qml
=> [Launcher] Limit the size of devices in the launcher

aseba/flatbuffers/thymio.fbs, aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclientendpoint.cpp, aseba/qt-thymio-dm-client-lib/thymiodevicemanagerclientendpoint.h, aseba/thymio-device-manager/app_endpoint.h
The TDM will send a Ping at regular interval and the TDM will
disconnect when a ping is not received
Fixes #505
=> [Launcher] Disconnect the TDM endpoint after a short period of inactivity

aseba/clients/qtcommon/common/CustomWidgets.cpp, aseba/clients/studio/ConstantsWidget.cpp, aseba/clients/studio/EventsWidget.cpp, aseba/clients/studio/NodeTab.cpp
=> [Studio] Improve layout of constants/events widgets

aseba/launcher/src/qml/ThymioSelectionView.qml
=> Change the button to go back to the main screen

aseba/launcher/src/qml/wirelessconfigurator/WirelessConfigurator.qml
=> Inform that older firmware can't be paired

aseba/launcher/src/qml/SettingsMenu.qml, aseba/launcher/src/qml/wirelessconfigurator/TitleBar.qml, aseba/launcher/src/qml/wirelessconfigurator/WirelessConfigurator.qml, aseba/launcher/src/qml/wirelessconfigurator/WirelessWizardWarningDialog.qml
=> Improve texts

aseba/clients/studio/VariablesModel.h
=> [Studio] Fix variable display when a filter is set

docs/en/aseba-language.rst
=> [Aseba] Document the const keyword

aseba/launcher/src/launcher.cpp
=> Display the description in the preferred UI languages

aseba/clients/qtcommon/translations/asebastudio_el.ts, aseba/clients/qtcommon/translations/asebastudio_es.ts, aseba/clients/qtcommon/translations/asebastudio_fr.ts, aseba/clients/qtcommon/translations/asebastudio_it.ts, aseba/clients/qtcommon/translations/asebastudio_ja.ts, aseba/clients/qtcommon/translations/asebastudio_tr.ts, aseba/clients/qtcommon/translations/asebastudio_zh.ts, aseba/clients/qtcommon/translations/compiler_el.ts, aseba/common/about/qtabout_el.ts, aseba/common/about/qtabout_es.ts, aseba/common/about/qtabout_fr.ts, aseba/common/about/qtabout_it.ts, aseba/common/about/qtabout_ja.ts, aseba/common/about/qtabout_tr.ts, aseba/common/about/qtabout_zh.ts, aseba/launcher/src/translations/launcher_de.ts, aseba/launcher/src/translations/launcher_el.ts, aseba/launcher/src/translations/launcher_es.ts, aseba/launcher/src/translations/launcher_fr.ts, aseba/launcher/src/translations/launcher_it.ts, aseba/launcher/src/translations/launcher_ja.ts, aseba/launcher/src/translations/launcher_pl.ts, aseba/launcher/src/translations/launcher_tr.ts, aseba/launcher/src/translations/launcher_zh.ts, aseba/targets/playground/asebaplayground_el.ts, aseba/targets/playground/asebaplayground_es.ts, aseba/targets/playground/asebaplayground_ja.ts, aseba/targets/playground/asebaplayground_tr.ts, aseba/targets/playground/asebaplayground_zh.ts
German as to be double checked
=> WIP: Translations 08 10 19

aseba/vm/vm.c
=> [VM] Kill events that take too many cycles to complete

aseba/thymio-device-manager/CMakeLists.txt, aseba/thymio-device-manager/app_endpoint.h, aseba/thymio-device-manager/main.cpp, aseba/thymio-device-manager/system_sleep_manager.h
=> Prevent sleep when an app is connected to the TDM

aseba/thymio-device-manager/serialacceptor_win32.cpp
=> On  windows, do not memorize the device before connecting to it

aseba/thymio-device-manager/aseba_node.cpp
=> Send a list of removed variables when loading new code

aseba/clients/studio/NodeTab.cpp, aseba/clients/studio/NodeTab.h, aseba/clients/studio/NodeTabsManager.cpp, aseba/clients/studio/NodeTabsManager.h, aseba/clients/studio/PlotTab.cpp, aseba/clients/studio/PlotTab.h
=> Always watch variables when a plot tab is visible

aseba/launcher/src/launcher.cpp, aseba/launcher/src/launcher.h, aseba/launcher/src/qml/Applications.qml, aseba/launcher/src/qml/WindowButtons.qml, ios/ios-cmake/LICENSE.md, ios/ios-cmake/README.md, ios/ios-cmake/ios.toolchain.cmake
Added some missing files, and beginning of UI changes
=> Ios adaptations

azure-pipelines.yml
Trying to get this profiles / certificate right
=> Pipeline build for IOS

azure-pipelines.yml, ios/exportOptions.plist
Changed parameters in the export file settings
=> Fixing iOS  ipa export

aseba/launcher/src/qml/Applications.qml, aseba/launcher/src/qml/ThymioSelectionDeviceDelegate.qml, aseba/launcher/src/qml/ThymioSelectionView.qml
=> [Launcher] E-puck devices are only compatible with studio

third_party/bonjour/CMakeLists.txt
=> Update the version of bonjour shipped on windows

aseba/launcher/src/qml/ThymioSelectionView.qml
=> [Launcher] Do not show a playground link when unavailable

aseba/launcher/src/qml/ThymioSelectionView.qml
Only tested on iPad, but should not disturb other platforms.
=> fix #719  For horizontal scrolling in thymio selection

aseba/launcher/src/qml/ThymioSelectionView.qml
Just of iOS for now, might probably be useful on android too 
fix #720
=> [iOS] added information message when no thymio are found

aseba/launcher/src/qml/ThymioSelectionDeviceDelegate.qml, aseba/launcher/src/qml/ThymioSelectionView.qml
Added functions in ThymioSelectionView.qml
The behaviour of the _Launch_ button in the Thymio Selection panel is now depending on the application choosen. 
If is the Aseba Studio the button text would be Watch or Compile and Program depending if the thymio selected is Available or Ready
=> Fixing bug 729 - predisposed translation but not added

aseba/clients/qtcommon/translations/asebastudio_de.ts, aseba/clients/qtcommon/translations/asebastudio_el.ts, aseba/clients/qtcommon/translations/asebastudio_es.ts, aseba/clients/qtcommon/translations/asebastudio_fr.ts, aseba/clients/qtcommon/translations/asebastudio_it.ts, aseba/clients/qtcommon/translations/asebastudio_ja.ts, aseba/clients/qtcommon/translations/asebastudio_pl.ts, aseba/clients/qtcommon/translations/asebastudio_tr.ts, aseba/clients/qtcommon/translations/asebastudio_zh.ts, aseba/launcher/src/translations/launcher_de.ts, aseba/launcher/src/translations/launcher_el.ts, aseba/launcher/src/translations/launcher_es.ts, aseba/launcher/src/translations/launcher_fr.ts, aseba/launcher/src/translations/launcher_it.ts, aseba/launcher/src/translations/launcher_ja.ts, aseba/launcher/src/translations/launcher_pl.ts, aseba/launcher/src/translations/launcher_tr.ts, aseba/launcher/src/translations/launcher_zh.ts
Runned generation script for new translatable strings for the studio and the launcher
./clients/qtcommon/translations/asebastudio_*.ts
./launcher/src/translations/launcher_*.ts
=> added automatically generated translations

aseba/launcher/src/qml/Applications.qml, flatpak/org.mobsya.ThymioSuite.json
Fixes the defect #795 and updates the checksum of the vpl3 export required by the defect #797
=> added the language to the vpl3 parameters

aseba/launcher/src/qml/Applications.qml
fixes defect #800 , the name for the websocket parameter in the url is 'w'
=> VPL3 connection remote computers is not working

aseba/launcher/src/launcher.cpp, aseba/launcher/src/launcher.h, aseba/launcher/src/main.cpp
saving local configuration for launcher application via QT data Structures
=> Fixing Bug 808

aseba/launcher/src/qml/ThymioSelectionView.qml, aseba/launcher/src/qml/WindowButtons.qml
=> add message like ios when no relay computer are found

js/pack.js
The interface of copyFileSync seems to have changed
=> Fix JS API build

aseba/thymio-device-manager/app_server.h
Signed-off-by: Michael Bonani <michael.bonani@mobsya.org>
=> use only ipv4 if problem with ipv6

aseba/launcher/src/qml/ApplicationSelectionView.qml, aseba/launcher/src/qml/remoteconnection/RemoteConnectionDialog.qml, aseba/launcher/src/qml/wirelessconfigurator/WirelessConfigurator.qml
Should solve a display issue on macOS Big Sure
=> In launcher, fonts "Roboto Light" and "Bold" replaced by "Roboto"

aseba/launcher/src/qml/Applications.qml, aseba/launcher/src/translations/launcher_de.ts, aseba/launcher/src/translations/launcher_en.ts, aseba/launcher/src/translations/launcher_fr.ts, aseba/launcher/src/translations/launcher_it.ts
Same URLs for Mac and Linux for the moment.
=> In launcher, urls to install Thonny for Mac/Linux, en/fr/de/it
